version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - my_networks

networks:
  my_networks:
    driver: overlay

